### ISSUE TITLE
Cachet URL CA certificate 

### ISSUE THREAD

**Issue by lukasmrtvy** [nzin/prometheus-cachethq#3]
Is possible to "somehow" use custom CA certificate for -cachethq_url ? I am running cachet behind https://
Thanks

**Comment by nzin** [comment]
Hi Lukas,
I am sure I/we can do that. I am in vacation for 2 weeks, but I/we can work on it beginning of January (if you dont mind ;-) ).
I have to do something like https://stackoverflow.com/questions/38822764/how-to-send-a-https-request-with-a-certificate-golang

**Comment by nzin** [comment]
Hi @lukasmrtvy , would you mind to test the https://github.com/nzin/prometheus-cachethq/tree/customCA branch?

You should be able to provide a custom CA, via the cachethq_root_ca parameter (or the CACHETHQ_ROOT_CA env variable)

**Comment by lukasmrtvy** [comment]
Hi @nzin ,
I will try this tomorrow.
In meanwhile.. There should be also something like CACHETHQ_DISABLE_TLS_VERIFICATION , to disable https:// certificate chcecking. Its good for dev purpose.
Thanks

**Comment by nzin** [comment]
done in the last commit, if you can test it as well :-) (called "cachethq_skip_verify_ssl")

**Comment by lukasmrtvy** [comment]
Hi @nzin 
I can confirm that CACHETHQ_SKIP_VERIFY_SSL works. 
I have to setup proper CA + signed certs to verify CACHETHQ_ROOT_CA variable .

**Comment by nzin** [comment]
great, let me know for the CA stuff, and then I will merge.

**Comment by lukasmrtvy** [comment]
Hi
I can confirm that CACHETHQ_ROOT_CA variable works too.
Thanks

**Comment by nzin** [comment]
I merged into master
