### ISSUE TITLE
LABEL_NAME  environment variable not working

### ISSUE THREAD

**Issue by sanjuicgithub** [nzin/prometheus-cachethq#9]
Environment variable 'LABEL_NAME' is not working and it's always taking default label as 'alertname'. I verified in the Bridge container that the new environment variable is set as environment variable however it's using it. 

Configuration made to overwritte the default label : changed the environment variable as mentioned below : 

    environment:
      - CACHETHQ_URL=http://cachet:8000
      - CACHETHQ_TOKEN=dsfasfasfasfasfasf34324
      - LOG_LEVEL=debug
      - PROMETHEUS_TOKEN=89898004e8af5ef479fe1322deb54e3f9
      - LABEL_NAME=application

Current Result : bridge is using 'alertname' label always to update the status in Cachet.
Expected Result :  bridge should use 'application' label to update the status in Cachet.

$ docker exec -it 98f env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=98feee220f9d
TERM=xterm
CACHETHQ_TOKEN=<token id>
CACHETHQ_URL=http://cachet:8000
LABEL_NAME=application
LOG_LEVEL=debug

May I kindly request you to check what's wrong here or If I have wrong interpretation about using this variable ? 

Regards,
Sanjay.

**Comment by nzin** [comment]
Hello,

weird, I will try to have a look.

**Comment by sanjuicgithub** [comment]
Hello @nzin  , 
Did you get chance to look at the above reported issue ?

**Comment by nzin** [comment]
my bad, I didn't took time.

I check the code, but I need to test it real. Sorry, I will try to get news
soon (but I am offsite for one week)

**Comment by nzin** [comment]
Hi sanjuic,

I have in CachetHQ a component named "ds-jenkins".
If I start prometheus-cachethq bridge with:
```
./prometheus-cachethq -prometheus_token _prometheus_bearer_token_ -cachethq_token _cachet_token_ -label_name bla -cachethq_url https://_my_cachethq_url_/
```

and I mimic Prometheus:
```
curl -X POST -H 'Authorization: Bearer _prometheus_bearer_token_' -H "Content-Type: application/json" -d '
{
  "receiver": "webhook",
  "status": "firing",
  "alerts": [
    {
      "status": "firing",
      "labels": {
        "bla": "ds-jenkins",
        "dc": "eu-west-1",
        "instance": "localhost:9090",
        "job": "prometheus24"
      },
      "annotations": {
        "description": "some description"
      },
      "startsAt": "2018-08-03T09:52:26.739266876+02:00",
      "endsAt": "0001-01-01T00:00:00Z",
      "generatorURL": "http://simon-laptop:9090/graph?g0.expr=go_memstats_alloc_bytes+%3E+0\u0026g0.tab=1"                                                                                   
    }
  ],
  "groupLabels": {
    "bla": "Test",
    "job": "prometheus24"
  },
  "commonLabels": {
    "bla": "Test",
    "dc": "eu-west-1",
    "instance": "localhost:9090",
    "job": "prometheus24"
  },
  "commonAnnotations": {
    "description": "some description"
  },
  "externalURL": "http://simon-laptop:9093",
  "version": "4",
  "groupKey": "{}:{alertname=\"Test\", job=\"prometheus24\"}"
}' http://localhost:8080/alert
```

So basically I am not using "alertname" but "bla" (dont pay attention to groupLabels, and commonLabels. This is 'alerts' that is important here)
I manage to update CachetHQ.

Maybe you are confused because prometheus-cachethq don't return an error message when it should (I can improve that)?

Regards,

**Comment by sanjuicgithub** [comment]
@nzin,
Hello Nicolas,  Thanks for your response.  I have also checked the command line options(-label_name) which you tested here, and this works fine for me too.

The problem is with 'LABEL_NAME' in docker container, this is not working.  Unfortunately I am not familiar with 'go' and therefore can't debug further.

**Comment by sanjuicgithub** [comment]
@nzin Hello Nicolas, 
Can you please push the 1.0.2 docker image to the docker registry ? There still it's 1.0.1.

**Comment by nzin** [comment]
sure. let me check

**Comment by nzin** [comment]
I pushed 1.0.2 (and 1.0.3 which is just a fix for the tests). Can you have a try?

**Comment by sanjuicgithub** [comment]
@nzin , Looks good now. 
Thanks Nicolas.
